# Generated by Django 5.2.1 on 2025-10-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='time_created',
            field=models.DateField(auto_now=True, verbose_name='time created'),
        ),
    ]
