# Generated by Django 5.2.1 on 2025-12-12 15:20

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persian_slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='persian slug')),
                ('english_slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='english slug')),
                ('arabic_slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='arabic slug')),
                ('show_on_english', models.BooleanField(default=False, verbose_name='show on English')),
                ('show_on_persian', models.BooleanField(default=False, verbose_name='show on Persian')),
                ('show_on_arabic', models.BooleanField(default=False, verbose_name='show on Arabic')),
                ('title_english', models.CharField(blank=True, max_length=255, null=True, verbose_name='English Title')),
                ('title_persian', models.CharField(blank=True, max_length=255, null=True, verbose_name='Persian Title')),
                ('title_arabic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Arabic Title')),
                ('avatar', models.ImageField(upload_to='blogs', verbose_name='blogs image')),
                ('description_english', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='English description')),
                ('description_persian', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Persian description')),
                ('description_arabic', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Arabic description')),
                ('short_description_english', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Short English description')),
                ('short_description_persian', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Short Persian description')),
                ('short_description_arabic', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Short Arabic description')),
                ('tags', models.TextField(blank=True, null=True, verbose_name='tags')),
                ('time_created', models.DateField(auto_now=True, verbose_name='time created')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='ReviewModelBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='phone')),
                ('comment', models.TextField(verbose_name='comment')),
                ('rate', models.CharField(max_length=255, verbose_name='rate')),
                ('show', models.BooleanField(default=False, verbose_name='SHOW')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Arabic_IndexBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enable', models.BooleanField(default=True, verbose_name='enable')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arabic_index', to='blogs.blogsmodel', verbose_name='baner blog')),
            ],
            options={
                'verbose_name': 'arabic baner blog',
                'verbose_name_plural': 'arabic baner blogs',
            },
        ),
        migrations.CreateModel(
            name='English_IndexBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enable', models.BooleanField(default=True, verbose_name='enable')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_index', to='blogs.blogsmodel', verbose_name='baner blog')),
            ],
            options={
                'verbose_name': 'english baner blog',
                'verbose_name_plural': 'english baner blogs',
            },
        ),
        migrations.CreateModel(
            name='Persian_IndexBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enable', models.BooleanField(default=True, verbose_name='enable')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persian_index', to='blogs.blogsmodel', verbose_name='baner blog')),
            ],
            options={
                'verbose_name': 'persian baner blog',
                'verbose_name_plural': 'persian baner blogs',
            },
        ),
        migrations.AddField(
            model_name='blogsmodel',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='commentof', to='blogs.reviewmodelblog', verbose_name='Comments'),
        ),
    ]
