# Generated by Django 5.2.1 on 2025-05-18 16:01

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsmodel',
            name='short_description_arabic',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Short Arabic description'),
        ),
        migrations.AddField(
            model_name='blogsmodel',
            name='short_description_english',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Short English description'),
        ),
        migrations.AddField(
            model_name='blogsmodel',
            name='short_description_persian',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Short Persian description'),
        ),
    ]
