# Generated by Django 5.2.1 on 2025-05-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogsmodel_short_description_arabic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsmodel',
            name='time_created',
            field=models.DateField(auto_now=True),
        ),
    ]
