# Generated by Django 5.2.1 on 2025-05-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogsmodel_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsmodel',
            name='avatar',
            field=models.ImageField(upload_to='blogs', verbose_name='blogs image'),
        ),
    ]
