# Generated by Django 5.2.1 on 2025-05-18 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blogsmodel_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='english_indexblog',
            old_name='product',
            new_name='blog',
        ),
    ]
