# Generated by Django 5.2.1 on 2025-10-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_rename_product_english_indexblog_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsmodel',
            name='time_created',
            field=models.DateField(auto_now=True, verbose_name='time created'),
        ),
    ]
