# Generated by Django 5.2.1 on 2025-12-12 15:19

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='phone')),
                ('comment', models.TextField(verbose_name='comment')),
                ('rate', models.CharField(max_length=255, verbose_name='rate')),
                ('show', models.BooleanField(default=False, verbose_name='SHOW')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persian_slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='persian slug')),
                ('english_slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='english slug')),
                ('arabic_slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='arabic slug')),
                ('show_on_english', models.BooleanField(default=False, verbose_name='show on English')),
                ('show_on_persian', models.BooleanField(default=False, verbose_name='show on Persian')),
                ('show_on_arabic', models.BooleanField(default=False, verbose_name='show on Arabic')),
                ('title_english', models.CharField(blank=True, max_length=255, null=True, verbose_name='English Title')),
                ('title_persian', models.CharField(blank=True, max_length=255, null=True, verbose_name='Persian Title')),
                ('title_arabic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Arabic Title')),
                ('price_english', models.IntegerField(blank=True, null=True, verbose_name='English Price')),
                ('price_persian', models.IntegerField(blank=True, null=True, verbose_name='Persian Price')),
                ('price_arabic', models.IntegerField(blank=True, null=True, verbose_name='Arabic Price')),
                ('is_new', models.BooleanField(default=False, verbose_name='enable if this product is new')),
                ('inventory', models.BooleanField(default=True, verbose_name='inventory')),
                ('avatar', models.ImageField(upload_to='products', verbose_name='product image')),
                ('description_english', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='English description')),
                ('description_persian', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Persian description')),
                ('description_arabic', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Arabic description')),
                ('star', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=5, verbose_name='Rate')),
                ('tags', models.TextField(blank=True, null=True, verbose_name='tags')),
                ('related_products', models.ManyToManyField(blank=True, null=True, related_name='product', to='shop.productsmodel', verbose_name='related products')),
                ('comments', models.ManyToManyField(blank=True, null=True, related_name='commentof', to='shop.reviewmodel', verbose_name='Comments')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Persian_Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enable', models.BooleanField(default=True, verbose_name='enable')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persian_index', to='shop.productsmodel', verbose_name='baner product')),
            ],
            options={
                'verbose_name': 'persian baner product',
                'verbose_name_plural': 'persian baner products',
            },
        ),
        migrations.CreateModel(
            name='English_Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enable', models.BooleanField(default=True, verbose_name='enable')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_index', to='shop.productsmodel', verbose_name='baner product')),
            ],
            options={
                'verbose_name': 'english baner product',
                'verbose_name_plural': 'english baner products',
            },
        ),
        migrations.CreateModel(
            name='Arabic_Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enable', models.BooleanField(default=True, verbose_name='enable')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arabic_index', to='shop.productsmodel', verbose_name='baner product')),
            ],
            options={
                'verbose_name': 'arabic baner product',
                'verbose_name_plural': 'arabic baner products',
            },
        ),
    ]
