# Generated by Django 5.1.4 on 2025-05-08 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arabic_Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enable', models.BooleanField(default=True, verbose_name='enable')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arabic_index', to='shop.productsmodel', verbose_name='baner product')),
            ],
            options={
                'verbose_name': 'arabic baner product',
                'verbose_name_plural': 'arabic baner products',
            },
        ),
        migrations.CreateModel(
            name='English_Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enable', models.BooleanField(default=True, verbose_name='enable')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_index', to='shop.productsmodel', verbose_name='baner product')),
            ],
            options={
                'verbose_name': 'english baner product',
                'verbose_name_plural': 'english baner products',
            },
        ),
        migrations.CreateModel(
            name='Persian_Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enable', models.BooleanField(default=True, verbose_name='enable')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persian_index', to='shop.productsmodel', verbose_name='baner product')),
            ],
            options={
                'verbose_name': 'persian baner product',
                'verbose_name_plural': 'persian baner products',
            },
        ),
    ]
