# Generated by Django 5.1.4 on 2025-05-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_arabic_index_english_index_persian_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='commentof', to='shop.reviewmodel', verbose_name='Comments'),
        ),
    ]
