# Generated by Django 5.1.4 on 2025-05-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productsmodel_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='tags',
            field=models.TextField(blank=True, null=True, verbose_name='tags'),
        ),
    ]
