# Generated by Django 5.2.1 on 2025-06-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productsmodel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='arabic_slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='arabic slug'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='english_slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='english slug'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='persian_slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='persian slug'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='related_products',
            field=models.ManyToManyField(blank=True, null=True, related_name='product', to='shop.productsmodel', verbose_name='related products'),
        ),
    ]
