# Generated by Django 5.2.1 on 2025-12-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persianredirect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='old_path',
            field=models.CharField(db_index=True, help_text='This should be an absolute path, excluding the domain name. Example: “/events/search/”.', max_length=1000, verbose_name='redirect from'),
        ),
    ]
